-- MySQL Script generated by MySQL Workbench
-- Wed Mar 31 13:42:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipousuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipousuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipousuario` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `dni` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `usuario` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `id_tipousuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Usuario_TipoUsuario1_idx` (`id_tipousuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_TipoUsuario1`
    FOREIGN KEY (`id_tipousuario`)
    REFERENCES `mydb`.`tipousuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipoproducto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipoproducto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipoproducto` (
  `id` INT NOT NULL,
  `codigo` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`producto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `codigo` VARCHAR(45) NULL,
  `existencias` INT NULL,
  `precio` DOUBLE NULL,
  `id_tipoproducto` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Producto_Tipoproducto_idx` (`id_tipoproducto` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_Tipoproducto`
    FOREIGN KEY (`id_tipoproducto`)
    REFERENCES `mydb`.`tipoproducto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`factura` ;

CREATE TABLE IF NOT EXISTS `mydb`.`factura` (
  `id` INT NOT NULL,
  `codigo` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Factura_Usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Factura_Usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`compra` ;

CREATE TABLE IF NOT EXISTS `mydb`.`compra` (
  `id` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `id_factura` INT NOT NULL,
  `codigo_envio` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `id_usuario`),
  INDEX `fk_Compra_Producto1_idx` (`id_producto` ASC) VISIBLE,
  INDEX `fk_Compra_Factura1_idx` (`id_factura` ASC) VISIBLE,
  CONSTRAINT `fk_Compra_Producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_Factura1`
    FOREIGN KEY (`id_factura`)
    REFERENCES `mydb`.`factura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carrito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`carrito` ;

CREATE TABLE IF NOT EXISTS `mydb`.`carrito` (
  `id` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Carrito_Producto1_idx` (`id_producto` ASC) VISIBLE,
  INDEX `fk_Carrito_Usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Carrito_Producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carrito_Usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `id` INT NOT NULL,
  `codigo` VARCHAR(45) NULL,
  `cantidad` INT NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`proveedor` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `email` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pedido_producto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pedido_producto` (
  `id_pedido` INT NOT NULL,
  `id_producto` INT NOT NULL,
  PRIMARY KEY (`id_pedido`, `id_producto`),
  INDEX `fk_Pedido_has_Producto_Producto1_idx` (`id_producto` ASC) VISIBLE,
  INDEX `fk_Pedido_has_Producto_Pedido1_idx` (`id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_has_Producto_Pedido1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `mydb`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Producto_Producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido_proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pedido_proveedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pedido_proveedor` (
  `id_pedido` INT NOT NULL,
  `id_proveedor` INT NOT NULL,
  PRIMARY KEY (`id_pedido`, `id_proveedor`),
  INDEX `fk_Pedido_has_Proveedor_Proveedor1_idx` (`id_proveedor` ASC) VISIBLE,
  INDEX `fk_Pedido_has_Proveedor_Pedido1_idx` (`id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_has_Proveedor_Pedido1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `mydb`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Proveedor_Proveedor1`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `mydb`.`proveedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
