-- MySQL Script generated by MySQL Workbench
-- Wed Mar 31 13:42:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `javitronics` DEFAULT CHARACTER SET utf8 ;
USE `javitronics` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipousuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javitronics`.`tipousuario` ;

CREATE TABLE IF NOT EXISTS `javitronics`.`tipousuario` (
  `id` BIGINT NOT NULL,
  `nombre` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `tipousuario` (`id`, `nombre`) VALUES
(1, 'Administrador'),
(2, 'Cliente');

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javitronics`.`usuario` ;

CREATE TABLE IF NOT EXISTS `javitronics`.`usuario` (
  `id` bigint(20) NOT NULL,
  `dni` varchar(10) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `nombre` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `apellido1` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `apellido2` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `login` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `password` varchar(512) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT 'da8ab09ab4889c6208116a675cad0b13e335943bd7fc418782d054b32fdfba04',
  `email` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `descuento` int(11) NOT NULL DEFAULT '0',
  `id_tipousuario` bigint(20) NOT NULL DEFAULT '2',
  PRIMARY KEY (`id`),
  INDEX `fk_Usuario_TipoUsuario1_idx` (`id_tipousuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_TipoUsuario1`
    FOREIGN KEY (`id_tipousuario`)
    REFERENCES `javitronics`.`tipousuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION) 
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;



INSERT INTO `usuario` (`id`, `dni`, `nombre`, `apellido1`, `apellido2`, `login`, `password`, `email`, `descuento`, `id_tipousuario`) VALUES
(1, '12359854R', 'Admin', 'Administrador', 'Administrador', 'admin', 'da8ab09ab4889c6208116a675cad0b13e335943bd7fc418782d054b32fdfba04', 'admin@javitronics.com', 0, 1),
(2, '23325596P', 'Javier', 'Mocholi', 'Ortega', 'javi', 'da8ab09ab4889c6208116a675cad0b13e335943bd7fc418782d054b32fdfba04', 'javi@javitronics.com', 0, 2),
(3, '21470032S', 'Juan', 'Ortegs', 'Ruiz', 'juan', 'da8ab09ab4889c6208116a675cad0b13e335943bd7fc418782d054b32fdfba04', 'juan@javitronics.com', 0, 2);



-- -----------------------------------------------------
-- Table `mydb`.`tipoproducto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javitronics`.`tipoproducto` ;

CREATE TABLE IF NOT EXISTS `javitronics`.`tipoproducto` (
  `id` BIGINT NOT NULL,
  `codigo` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `nombre` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
 )
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javitronics`.`producto` ;

CREATE TABLE IF NOT EXISTS `javitronics`.`producto` (
  `id` BIGINT NOT NULL,
  `nombre` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `codigo` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `existencias` INT NOT NULL,
  `precio` DOUBLE NOT NULL,
  `descuento` int(11) NOT NULL,
  `id_tipoproducto` BIGINT NOT NULL,
 )
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- -----------------------------------------------------
-- Table `mydb`.`factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javitronics`.`factura` ;

CREATE TABLE IF NOT EXISTS `javitronics`.`factura` (
  `id` BIGINT NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `fecha` DATETIME NOT NULL,
 `iva` int(11) NOT NULL,
  `id_usuario` BIGINT NOT NULL,
`pagado` tinyint(1) NOT NULL
  )
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- -----------------------------------------------------
-- Table `mydb`.`compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javitronics`.`compra` ;

CREATE TABLE IF NOT EXISTS `javitronics`.`compra` (
  `id` BIGINT NOT NULL,
`cantidad` int(11) NOT NULL,
  `precio` double(10,2) NOT NULL,
  `fecha` datetime NOT NULL,
  `descuento_usuario` int(11) NOT NULL,
  `descuento_producto` int(11) NOT NULL,
  `id_producto` BIGINT NOT NULL,
  `id_factura` BIGINT NOT NULL,
  `codigo_envio` VARCHAR(45) NOT NULL,
  )
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- -----------------------------------------------------
-- Table `mydb`.`carrito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javitronics`.`carrito` ;

CREATE TABLE IF NOT EXISTS `javitronics`.`carrito` (
  `id` BIGINT NOT NULL,
`cantidad` int(11) NOT NULL,
`precio` double(10,2) NOT NULL,
  `id_producto` BIGINT NOT NULL,
  `id_usuario` BIGINT NOT NULL,
 )
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javitronics`.`pedido` ;

CREATE TABLE IF NOT EXISTS `javitronics`.`pedido` (
  `id` BIGINT NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `cantidad` BIGINT NOT NULL,
  `fecha` datetime NOT NULL,
  )
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- -----------------------------------------------------
-- Table `mydb`.`proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javitronics`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `javitronics`.`proveedor` (
  `id` BIGINT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  )
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- -----------------------------------------------------
-- Table `mydb`.`pedido_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javitronics`.`pedido_producto` ;

CREATE TABLE IF NOT EXISTS `javitronics`.`pedido_producto` (
  `id_pedido` BIGINT NOT NULL,
  `id_producto` BIGINT NOT NULL,
  
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- -----------------------------------------------------
-- Table `mydb`.`pedido_proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javitronics`.`pedido_proveedor` ;

CREATE TABLE IF NOT EXISTS `javitronics`.`pedido_proveedor` (
  `id_pedido` BIGINT NOT NULL,
  `id_proveedor` BIGINT NOT NULL,
  
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


-- Indices de la tabla `carrito`
--
ALTER TABLE `carrito`
  ADD PRIMARY KEY (`id`);

--
-- Indices de la tabla `compra`
--
ALTER TABLE `compra`
  ADD PRIMARY KEY (`id`);

--
-- Indices de la tabla `factura`
--
ALTER TABLE `factura`
  ADD PRIMARY KEY (`id`);

--
-- Indices de la tabla `producto`
--
ALTER TABLE `producto`
  ADD PRIMARY KEY (`id`);

--
-- Indices de la tabla `tipoproducto`
--
ALTER TABLE `tipoproducto`
  ADD PRIMARY KEY (`id`);

--
-- Indices de la tabla `tipousuario`
--
ALTER TABLE `tipousuario`
  ADD PRIMARY KEY (`id`);

--
-- Indices de la tabla `usuario`
--
ALTER TABLE `usuario`
  ADD PRIMARY KEY (`id`);

--
-- Indices de la tabla `pedido`
--
ALTER TABLE `pedido`
  ADD PRIMARY KEY (`id`);

--
-- Indices de la tabla `proveedor`
--
ALTER TABLE `proveedor`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `carrito`
--
ALTER TABLE `carrito`
  MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT de la tabla `compra`
--
ALTER TABLE `compra`
  MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT de la tabla `factura`
--
ALTER TABLE `factura`
  MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT de la tabla `producto`
--
ALTER TABLE `producto`
  MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT de la tabla `tipoproducto`
--
ALTER TABLE `tipoproducto`
  MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT de la tabla `tipousuario`
--
ALTER TABLE `tipousuario`
  MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- AUTO_INCREMENT de la tabla `usuario`
--
ALTER TABLE `usuario`
  MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;


--
-- AUTO_INCREMENT de la tabla `pedido`
--
ALTER TABLE `pedido`
  MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT;


--
-- AUTO_INCREMENT de la tabla `proveedor`
--
ALTER TABLE `proveedor`
  MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT;
COMMIT;







SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
